#pragma once
// @lat: [[engine/skills#plain_bushing_bore_with_lube_groove]]
//
// plain_bushing_bore_with_lube_groove — COMPOUND plain (journal) bushing
// bore with an internal helical lubrication groove:
//
//   sub 1: bore at bore_dia (running clearance over shaft)
//   sub 2: helical lube groove (1 lead, depth ≈ 0.3 mm)  ← uses HelicalSweep
//   sub 3: 30° entry-side chamfer (lead-in for shaft insertion)
//
// The groove provides distributed lubrication along the bushing length.
// Standard groove geometry per SAE J506 (plain-bearing supply grooves):
//   - groove width  = 0.8 mm  (nominal — fine-tuned by groove_pitch)
//   - groove depth  = 0.3 mm
//   - groove path   = 1 helical lead over the bore length (single start)
//
// The helical groove is generated by the HelicalSweep primitive (ISO 60°
// profile fallback cascade).  Per HelicalSweep contract, the returned
// `HelicalSweepProfile` indicates which path succeeded — we record it in
// pattern.helical_profile_used.
//
// DFM checks:
//   DFM-INPUT          : bore_dia ≤ 0, length ≤ 0, pitch ≤ 0
//   DFM-002            : bore_dia < 0.8 mm (sub-min bore)
//   DFM-BUSHING-RATIO  : length/bore_dia > 8 (extremely long bushing — flag
//                        warning; chip evacuation + tool deflection)
//   DFM-GROOVE-PITCH   : pitch < bore_dia × 0.5 (groove turns are too tight
//                        and intersect themselves at multiple revolutions)
//
// Recognize: metadata replay (compound features hard to fingerprint
// geometrically; helical groove particularly so).

#include "Datum.hpp"
#include "Skill.hpp"

#include <gp_Dir.hxx>

#include <string>
#include <vector>

namespace koocadcam::skill {

class Workpiece;

namespace plain_bushing_bore_with_lube_groove {

constexpr const char* kSkillId = "plain_bushing_bore_with_lube_groove";

struct Input
{
    FaceDatum   entry_face;
    double      position_x_mm   = 0.0;
    double      position_y_mm   = 0.0;
    gp_Dir      axis_dir        { 0.0, 0.0, -1.0 };
    double      bore_dia_mm     = 0.0;
    double      length_mm       = 0.0;    // bushing axial length
    double      groove_pitch_mm = 0.0;    // axial advance per turn
};

SkillOutput apply   (const Workpiece& wp, const Input& in);
DFMReport   validate(const Workpiece& wp, const Input& in);
std::vector<RecognizedFeature> recognize(const Workpiece& wp);

}  // namespace plain_bushing_bore_with_lube_groove
}  // namespace koocadcam::skill
