// @lat: [[engine/skills#spur_gear_involute]]

#include "spur_gear_involute.hpp"

#include "Workpiece.hpp"
#include "engine/primitives/Cuts.hpp"
#include "engine/primitives/Tools.hpp"

#include <BRepAdaptor_Surface.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <BRepPrimAPI_MakePrism.hxx>
#include <Standard_Failure.hxx>
#include <gp.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Cylinder.hxx>
#include <gp_Pnt.hxx>
#include <gp_Trsf.hxx>
#include <gp_Vec.hxx>

#include <nlohmann/json.hpp>
#include <spdlog/spdlog.h>

#include <algorithm>
#include <cmath>
#include <vector>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

namespace koocadcam::skill::spur_gear_involute {

namespace pr = koocadcam::engine::prim;
using nlohmann::json;

namespace {

// Number of involute sample points per flank.
constexpr int kFlankSamples = 24;

// Build a 2D polyline approximating one tooth-gap (gullet) cross-section,
// centred on +X axis (i.e. the gullet's CENTERLINE is angle 0 around +Z).
// Returns a closed wire ready to be made into a face and prism.
//
// Geometry of one gullet:
//   inner arc  : root circle    r_root
//   outer arc  : tip  circle    r_tip
//   left flank : involute from base circle out to tip (mirrored to -y side)
//   right flank: involute from base circle out to tip (on +y side)
//
// Both flanks shifted angularly so the GAP (gullet) opens toward +X.
TopoDS_Shape buildToothGapPrism(double moduleM, int z, double pressureAngleRad,
                                double faceWidth, double overhang)
{
    const double rPitch = moduleM * static_cast<double>(z) / 2.0;
    const double rBase  = rPitch * std::cos(pressureAngleRad);
    const double rTip   = rPitch + moduleM;
    const double rRoot  = std::max(rBase * 0.95, rPitch - 1.25 * moduleM);
    const double toothAngle = 2.0 * M_PI / static_cast<double>(z);

    // Find t_max where involute reaches r_tip:
    //   r(t) = r_base · sqrt(1 + t²)  →  t_max = sqrt((r_tip/r_base)² − 1)
    const double tMax = std::sqrt(std::max(0.0,
        (rTip / rBase) * (rTip / rBase) - 1.0));

    // Tooth thickness at pitch radius (chord) = π·m / 2.
    // Angular tooth thickness at pitch = π·m / (2·r_pitch) = π / z.
    // Half-angular-tooth-thickness at base circle (using involute function):
    //   inv(α) = tan(α) − α
    //   half_tooth_at_base = π/(2·z) + inv(α)
    const double invAlpha = std::tan(pressureAngleRad) - pressureAngleRad;
    const double halfToothAtBase = M_PI / (2.0 * static_cast<double>(z)) + invAlpha;

    // The TOOTH is centred at angle = +halfTooth on +Y side and -halfTooth on -Y side
    // relative to the gullet centerline.  We build a SINGLE gullet centred at
    // angle = 0 (around +X), so the tooth FLANK on the +Y side is the LEFT flank
    // of the +Y-neighbour tooth.  In involute math, that flank is generated by
    // the involute starting at angle = halfToothAtBase on the BASE circle.

    // Right flank polyline (on +Y side of gullet) — generated by involute at
    // base-circle angle = +halfToothAtBase, swept by t to r_tip.
    std::vector<gp_Pnt> rightFlank;
    rightFlank.reserve(kFlankSamples);
    for (int k = 0; k < kFlankSamples; ++k) {
        const double t = tMax * static_cast<double>(k) / static_cast<double>(kFlankSamples - 1);
        // Standard involute centred on +X:
        const double xi = rBase * (std::cos(t) + t * std::sin(t));
        const double yi = rBase * (std::sin(t) - t * std::cos(t));
        // Rotate by +halfToothAtBase so flank lands on +Y side of gullet centre.
        const double c = std::cos(halfToothAtBase);
        const double s = std::sin(halfToothAtBase);
        const double xr =  xi * c - yi * s;
        const double yr =  xi * s + yi * c;
        rightFlank.emplace_back(xr, yr, -overhang);
    }

    // Left flank — mirror of right flank about X axis.
    std::vector<gp_Pnt> leftFlank;
    leftFlank.reserve(kFlankSamples);
    for (int k = 0; k < kFlankSamples; ++k) {
        const gp_Pnt& p = rightFlank[k];
        leftFlank.emplace_back(p.X(), -p.Y(), -overhang);
    }

    // Bottom of gullet: arc of root circle from leftFlank[0] back to
    // rightFlank[0].  Approximate as a 3-segment polyline through angle 0.
    // leftFlank[0] is at angle = -halfToothAtBase on base circle (radius
    // rBase).  We extend INWARD to root radius along the same radial.
    // Build bottom land points: from rightFlank[0] (at +halfToothAtBase, rBase)
    // → out to (+halfToothAtBase, rRoot) → through (0, rRoot) → (-halfToothAtBase, rRoot)
    // → (leftFlank[0]).
    const double rBaseRight_x = rBase * std::cos(halfToothAtBase);
    const double rBaseRight_y = rBase * std::sin(halfToothAtBase);
    const double rRootRight_x = rRoot * std::cos(halfToothAtBase);
    const double rRootRight_y = rRoot * std::sin(halfToothAtBase);
    const double rRootCenter_x = rRoot;
    const double rRootCenter_y = 0.0;
    const double rRootLeft_x  = rRoot * std::cos(-halfToothAtBase);
    const double rRootLeft_y  = rRoot * std::sin(-halfToothAtBase);

    // OUTER closing edge: from rightFlank.last to leftFlank.last along tip
    // circle.  These two points are at angles +halfToothAtTip and -halfToothAtTip
    // — we just use a straight line (chord) over the tooth tip.  But the tip
    // is on the TOOTH side, not the gullet side; the gullet's OUTER side
    // actually goes from rightFlank.last → OUT past the tip to a "ceiling"
    // beyond rTip, then back down to leftFlank.last.  We use a ceiling at
    // r = rTip + overhang/r ≈ rTip + 1 mm to ensure the cut goes ALL the
    // way through the blank.
    const double rCeil = rTip + 2.0;
    const gp_Pnt rightLast = rightFlank[kFlankSamples - 1];
    const gp_Pnt leftLast  = leftFlank[kFlankSamples - 1];
    const double angRightLast = std::atan2(rightLast.Y(), rightLast.X());
    const double angLeftLast  = std::atan2(leftLast .Y(), leftLast .X());
    const gp_Pnt rightCeil(rCeil * std::cos(angRightLast),
                           rCeil * std::sin(angRightLast),
                           -overhang);
    const gp_Pnt leftCeil(rCeil * std::cos(angLeftLast),
                          rCeil * std::sin(angLeftLast),
                          -overhang);
    const gp_Pnt topCeil(rCeil, 0.0, -overhang);

    // Build the closed wire (CCW when looking down +Z, from outside the
    // workpiece).  Order:
    //   bottom-root-right → up rightFlank → out to rightCeil → over topCeil
    //   → leftCeil → down leftFlank (reversed) → root-left → root-center
    //   → root-right (back to start)
    BRepBuilderAPI_MakeWire wire;

    // 1. root: leftRoot → centerRoot → rightRoot
    wire.Add(BRepBuilderAPI_MakeEdge(
        gp_Pnt(rRootLeft_x,  rRootLeft_y,  -overhang),
        gp_Pnt(rRootCenter_x, rRootCenter_y, -overhang)).Edge());
    wire.Add(BRepBuilderAPI_MakeEdge(
        gp_Pnt(rRootCenter_x, rRootCenter_y, -overhang),
        gp_Pnt(rRootRight_x,  rRootRight_y, -overhang)).Edge());

    // 2. step out from rootRight to baseRight (start of involute right flank)
    wire.Add(BRepBuilderAPI_MakeEdge(
        gp_Pnt(rRootRight_x, rRootRight_y, -overhang),
        gp_Pnt(rBaseRight_x, rBaseRight_y, -overhang)).Edge());

    // 3. right flank (involute) from baseRight up to rightLast
    //    rightFlank[0] should be ≈ (rBaseRight_x, rBaseRight_y).
    for (int k = 0; k < kFlankSamples - 1; ++k) {
        wire.Add(BRepBuilderAPI_MakeEdge(rightFlank[k], rightFlank[k + 1]).Edge());
    }

    // 4. out to ceiling on right side
    wire.Add(BRepBuilderAPI_MakeEdge(rightLast, rightCeil).Edge());

    // 5. over the top: rightCeil → topCeil → leftCeil
    wire.Add(BRepBuilderAPI_MakeEdge(rightCeil, topCeil).Edge());
    wire.Add(BRepBuilderAPI_MakeEdge(topCeil,   leftCeil).Edge());

    // 6. down into leftLast
    wire.Add(BRepBuilderAPI_MakeEdge(leftCeil, leftLast).Edge());

    // 7. left flank reversed (from leftLast back down to leftFlank[0])
    for (int k = kFlankSamples - 1; k > 0; --k) {
        wire.Add(BRepBuilderAPI_MakeEdge(leftFlank[k], leftFlank[k - 1]).Edge());
    }

    // 8. step in from leftBase to leftRoot, closing the wire.
    const double rBaseLeft_x = rBase * std::cos(-halfToothAtBase);
    const double rBaseLeft_y = rBase * std::sin(-halfToothAtBase);
    wire.Add(BRepBuilderAPI_MakeEdge(
        gp_Pnt(rBaseLeft_x, rBaseLeft_y, -overhang),
        gp_Pnt(rRootLeft_x, rRootLeft_y, -overhang)).Edge());

    if (!wire.IsDone())
        throw Standard_Failure("spur_gear_involute: gullet wire build failed");

    BRepBuilderAPI_MakeFace face(wire.Wire(), true);
    if (!face.IsDone())
        throw Standard_Failure("spur_gear_involute: gullet face build failed");

    BRepPrimAPI_MakePrism prism(face.Face(),
        gp_Vec(0.0, 0.0, faceWidth + 2.0 * overhang));
    prism.Build();
    if (!prism.IsDone())
        throw Standard_Failure("spur_gear_involute: gullet prism build failed");

    (void)toothAngle;  // used downstream for replication
    return prism.Shape();
}

}  // namespace

// ── Validation ───────────────────────────────────────────────────────────

DFMReport validate(const Workpiece& wp, const Input& in)
{
    DFMReport r;
    if (in.module_mm <= 0.3 || in.module_mm > 50.0) {
        r.add("DFM-GEAR-MOD", "error",
              "spur_gear_involute: module_mm " +
              std::to_string(in.module_mm) + " out of (0.3, 50] mm");
    }
    if (in.teeth_count < 8 || in.teeth_count > 200) {
        r.add("DFM-GEAR-CT", "error",
              "spur_gear_involute: teeth_count " +
              std::to_string(in.teeth_count) + " out of [8, 200]");
    }
    if (in.face_width_mm <= 0.0) {
        r.add("DFM-GEAR-FW", "error",
              "spur_gear_involute: face_width_mm must be > 0");
    }
    if (in.pressure_angle_deg < 14.5 || in.pressure_angle_deg > 30.0) {
        r.add("DFM-GEAR-PA", "error",
              "spur_gear_involute: pressure_angle " +
              std::to_string(in.pressure_angle_deg) + " out of [14.5, 30] deg");
    }
    if (in.module_mm > 0.0 && in.teeth_count > 0) {
        const double rTip = in.module_mm * (in.teeth_count / 2.0 + 1.0);
        const double blankR = in.blank_outer_dia_mm > 0.0
            ? in.blank_outer_dia_mm / 2.0
            : rTip;
        if (blankR + 1e-6 < rTip) {
            r.add("DFM-GEAR-OD", "error",
                  "spur_gear_involute: blank_outer_dia " +
                  std::to_string(in.blank_outer_dia_mm) +
                  " smaller than required 2·r_tip " + std::to_string(2.0 * rTip));
        }
    }
    (void)wp;
    return r;
}

// ── Synthesis ────────────────────────────────────────────────────────────

SkillOutput apply(const Workpiece& wp, const Input& in)
{
    DFMReport dfm = validate(wp, in);
    if (!dfm.passed) {
        std::string msg = "spur_gear_involute DFM failed:";
        for (const auto& f : dfm.findings) msg += "\n  - " + f.code + ": " + f.message;
        throw SkillError(msg);
    }

    const double m       = in.module_mm;
    const int    z       = in.teeth_count;
    const double rPitch  = m * z / 2.0;
    const double rTip    = rPitch + m;
    const double rRoot   = rPitch - 1.25 * m;
    const double Z       = in.face_width_mm;
    const double alpha   = in.pressure_angle_deg * M_PI / 180.0;
    const double kOver   = 0.05;

    // Seed gullet at angle 0 (along +X).
    const TopoDS_Shape seedGullet =
        buildToothGapPrism(m, z, alpha, Z, kOver);

    // Replicate z times by rotation around +Z.
    const gp_Ax1 zAxis(gp_Pnt(0, 0, 0), gp::DZ());
    const double dTheta = 2.0 * M_PI / static_cast<double>(z);

    std::vector<TopoDS_Shape> cutters;
    cutters.reserve(static_cast<size_t>(z));
    for (int i = 0; i < z; ++i) {
        if (i == 0) {
            cutters.push_back(seedGullet);
            continue;
        }
        gp_Trsf rot;
        rot.SetRotation(zAxis, static_cast<double>(i) * dTheta);
        BRepBuilderAPI_Transform xf(seedGullet, rot, true);
        if (!xf.IsDone())
            throw SkillError("spur_gear_involute: cutter rotation failed");
        cutters.push_back(xf.Shape());
    }

    const TopoDS_Shape newShape = pr::cutMany(wp.shape(), cutters);

    // Volume removed (approx): z gullets, each ≈ (r_tip² − r_root²)·(toothAngle/2)·Z·0.5
    const double gulletVol =
        0.5 * (rTip * rTip - rRoot * rRoot) * (dTheta * 0.5) * Z;
    const double volRemoved = z * gulletVol;

    json params = {
        { "module_mm",          m },
        { "teeth_count",        z },
        { "face_width_mm",      Z },
        { "pressure_angle_deg", in.pressure_angle_deg },
        { "blank_outer_dia_mm", in.blank_outer_dia_mm > 0.0
                                  ? in.blank_outer_dia_mm : 2.0 * rTip },
    };
    json pattern = {
        { "kind",                  kSkillId },
        { "is_gear",               true },
        { "is_compound",           true },
        { "subfeature_count",      z },
        { "module_mm",             m },
        { "teeth_count",           z },
        { "pressure_angle_deg",    in.pressure_angle_deg },
        { "pitch_dia_mm",          2.0 * rPitch },
        { "tip_dia_mm",            2.0 * rTip },
        { "root_dia_mm",           2.0 * rRoot },
        { "face_width_mm",         Z },
        { "derived_volume_removed", volRemoved },
        { "standard",              "ISO 53" },
        { "profile",               "involute_sampled" },
    };

    ToolingMeta tooling;
    tooling.tool_type         = "gear_hob";
    tooling.tool_dia_mm       = m * 5.0;
    tooling.tool_length_mm    = Z * 2.0 + 10.0;
    tooling.tool_material     = "hss";
    tooling.flute_count       = 12;
    tooling.cutting_speed_sfm = 100.0;
    tooling.feed_per_tooth_mm = 0.04;
    tooling.stock_removed_mm3 = volRemoved;
    tooling.est_cycle_time_s  = std::max(30.0, z * 1.5 + 20.0);

    FeatureSignature sig{ kSkillId, params, pattern, tooling };

    auto wpNew = std::make_shared<Workpiece>(newShape, wp.material());
    wpNew->addFeature(sig);

    spdlog::debug("skill::spur_gear_involute applied: m={} z={} faces {}→{}",
                  m, z, wp.faceCount(), wpNew->faceCount());

    return SkillOutput{ wpNew, sig };
}

// ── Recognition ──────────────────────────────────────────────────────────
//
// Geometric: count Z-axis cylindrical faces + planar flanks clustered by
// angular sector around the gear axis.  Cluster count ≈ 2·z (each tooth
// contributes 2 flanks).  Fallback: metadata replay.

std::vector<RecognizedFeature> recognize(const Workpiece& wp)
{
    std::vector<RecognizedFeature> out;

    // ── Primary: geometric
    double xMin, yMin, zMin, xMax, yMax, zMax;
    wp.boundingBox(xMin, yMin, zMin, xMax, yMax, zMax);
    const double xMid = 0.5 * (xMin + xMax);
    const double yMid = 0.5 * (yMin + yMax);

    std::vector<double> flankAngles;
    int zCylCount = 0;
    for (int i = 0; i < wp.faceCount(); ++i) {
        if (wp.isFaceCylinder(i)) {
            BRepAdaptor_Surface s(wp.face(i));
            const gp_Cylinder cy = s.Cylinder();
            const gp_Dir d = cy.Axis().Direction();
            if (std::abs(std::abs(d.Z()) - 1.0) < 1e-2) ++zCylCount;
        } else if (wp.isFacePlanar(i)) {
            try {
                gp_Dir n = wp.faceNormal(i);
                if (std::abs(n.Z()) >= 0.3) continue;
                const gp_Pnt c = wp.faceCenter(i);
                const double dx = c.X() - xMid;
                const double dy = c.Y() - yMid;
                if (std::hypot(dx, dy) < 1.0) continue;
                flankAngles.push_back(std::atan2(dy, dx));
            } catch (...) {}
        }
    }

    if (flankAngles.size() >= 16) {
        std::sort(flankAngles.begin(), flankAngles.end());
        int clusterCount = 0;
        const double tol = 5.0 * M_PI / 180.0;
        for (size_t k = 0; k < flankAngles.size(); ++k) {
            if (k == 0 || std::abs(flankAngles[k] - flankAngles[k - 1]) > tol)
                ++clusterCount;
        }
        const int zEst = std::max(8, clusterCount / 2);
        if (zEst >= 8 && zEst <= 200) {
            const double od = std::max({ xMax - xMin, yMax - yMin });
            const double moduleEst = od / (static_cast<double>(zEst) + 2.0);
            const double thickness = zMax - zMin;
            json recovered = {
                { "module_mm",          moduleEst },
                { "teeth_count",        zEst },
                { "face_width_mm",      thickness },
                { "pressure_angle_deg", 20.0 },
                { "blank_outer_dia_mm", od },
            };
            json matched = {
                { "source",                "geometric_primary" },
                { "z_cyl_face_count",      zCylCount },
                { "flank_face_count",      static_cast<int>(flankAngles.size()) },
                { "angular_cluster_count", clusterCount },
                { "estimated_teeth_count", zEst },
            };
            out.push_back(RecognizedFeature{
                kSkillId, recovered, 0.7, matched
            });
        }
    }

    // ── Fallback: metadata replay
    for (const auto& f : wp.features()) {
        if (f.skill_id != kSkillId) continue;
        out.push_back(RecognizedFeature{
            kSkillId, f.params, 1.0,
            { { "source",       "feature_history_replay" },
              { "teeth_count",  f.pattern.value("teeth_count", 0) },
              { "module_mm",    f.pattern.value("module_mm",   0.0) } }
        });
    }
    return out;
}

}  // namespace koocadcam::skill::spur_gear_involute
